// This file is auto-generated by Firebase Hosting upon deployment.
// It initializes the Firebase SDK using your project's configuration.

self.firebase = self.firebase || {};

(function() {
  // Firebase configuration (auto-inserted)
  var firebaseConfig = {
    apiKey: "AIzaSyA4hegU59fgiVEC7weSAWDIJ7TcNPPzHww",
    authDomain: "todo-97eb7.firebaseapp.com",
    projectId: "todo-97eb7",
    storageBucket: "todo-97eb7.appspot.com",
    messagingSenderId: "532736396477",
    appId: "1:532736396477:web:c0444e0d91e744c356bb4"
  };

  // Initialize Firebase
  if (!self.firebase.apps || self.firebase.apps.length === 0) {
    self.firebase.initializeApp(firebaseConfig);
  }
})();
